In [4]:
import pandas as pd
import pandas as pd 
walk_df = pd.read_csv("data/EPA_SmartLocationDatabase_V3_Jan_2021_Final.csv")
walk_df

,OBJECTID,GEOID10,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,...,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,1,4.811300e+11,4.811300e+11,48,113,7825,4,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.184697,0.000476,0.137707,6,14,15,17,14.000000,3110.360820,2.978361e+05
1,2,4.811300e+11,4.811300e+11,48,113,7825,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.323221,0.000801,0.231868,3,10,12,14,10.833333,3519.469110,4.849451e+05
2,3,4.811300e+11,4.811300e+11,48,113,7825,3,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.314628,0.000736,0.213146,1,1,7,17,8.333333,1697.091802,1.067059e+05
3,4,4.811300e+11,4.811300e+11,48,113,7824,1,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.229821,0.000708,0.205018,16,10,17,17,15.666667,2922.609204,4.818284e+05
4,5,4.811300e+11,4.811300e+11,48,113,7824,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.164863,0.000433,0.125296,4,7,11,14,10.166667,3731.971773,6.876848e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220735,220736,7.803100e+11,7.803100e+11,78,30,961000,2,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,20,1,7.333333,3414.446949,3.355857e+05
220736,220737,7.803100e+11,7.803100e+11,78,30,961000,3,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,20,1,7.333333,2421.025608,2.924305e+05
220737,220738,7.803100e+11,7.803100e+11,78,30,961000,5,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,20,1,7.333333,1955.909418,1.619395e+05
220738,220739,7.803100e+11,7.803100e+11,78,30,960700,3,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,10,1,4.000000,16896.768870,1.038966e+07
220739,220740,7.803100e+11,7.803100e+11,78,30,960200,2,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,12,1,4.666667,3890.488237,6.114601e+05

In [11]:
walk_df.dropna()

,OBJECTID,GEOID10,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,...,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,1,4.811300e+11,4.811300e+11,48,113,7825,4,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.184697,0.000476,0.137707,6,14,15,17,14.000000,3110.360820,297836.0831
1,2,4.811300e+11,4.811300e+11,48,113,7825,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.323221,0.000801,0.231868,3,10,12,14,10.833333,3519.469110,484945.1466
2,3,4.811300e+11,4.811300e+11,48,113,7825,3,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.314628,0.000736,0.213146,1,1,7,17,8.333333,1697.091802,106705.9281
3,4,4.811300e+11,4.811300e+11,48,113,7824,1,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.229821,0.000708,0.205018,16,10,17,17,15.666667,2922.609204,481828.4303
4,5,4.811300e+11,4.811300e+11,48,113,7824,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.164863,0.000433,0.125296,4,7,11,14,10.166667,3731.971773,687684.7752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220646,220647,7.202100e+11,7.202100e+11,72,21,30200,2,490.0,"San Juan-Bayamón, PR",41980.0,...,-99999.000000,-99999.000000,-99999.000000,1,1,18,1,6.666667,1632.404551,139386.4852
220647,220648,7.202100e+11,7.202100e+11,72,21,31401,2,490.0,"San Juan-Bayamón, PR",41980.0,...,-99999.000000,-99999.000000,-99999.000000,1,1,17,1,6.333333,1474.513645,109441.0787
220648,220649,7.202100e+11,7.202100e+11,72,21,31202,1,490.0,"San Juan-Bayamón, PR",41980.0,...,-99999.000000,-99999.000000,-99999.000000,1,1,16,1,6.000000,2112.392508,199405.4456
220649,220650,7.205320e+11,7.205320e+11,72,53,150400,3,490.0,"San Juan-Bayamón, PR",41980.0,...,-99999.000000,-99999.000000,-99999.000000,1,1,14,1,5.333333,4448.103039,498971.9856
220650,220651,7.205320e+11,7.205320e+11,72,53,150104,4,490.0,"San Juan-Bayamón, PR",41980.0,...,-99999.000000,-99999.000000,-99999.000000,1,1,13,1,5.000000,3645.554606,621538.6947

In [14]:
new_walk_df= walk_df[['OBJECTID','GEOID10','GEOID20','STATEFP','BLKGRPCE','CSA_Name','TotPop','P_WrkAge',
                            'D2A_Ranked','D2B_Ranked','D3B_Ranked','D4A_Ranked','NatWalkInd']]

In [15]:
for col in new_walk_df.columns:
    print(col)

OBJECTID
GEOID10
GEOID20
STATEFP
BLKGRPCE
CSA_Name
TotPop
P_WrkAge
D2A_Ranked
D2B_Ranked
D3B_Ranked
D4A_Ranked
NatWalkInd

In [17]:
new_walk_df.to_csv('walkability_file.csv')